<a href="https://colab.research.google.com/github/Sushilrajpange/100-400-even-no/blob/main/allnumpyarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
type(arr)
print(arr)


[1 2 3 4 5]


In [2]:
arr.shape

(5,)

In [3]:
#multidiamention
my_list1=[1,3,4,5,2]
my_list2=[3,4,5,6,7]
my_list3=[6,7,8,9,1]
arr*np.array([my_list1,my_list2,my_list3])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.shape

(5,)

In [7]:
arr.reshape(5)

array([1, 2, 3, 4, 5])

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[3]

4

In [15]:
arr=np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [9,7,6,8,9]])
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [16]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
arr[:2,0:2]

array([[1, 2],
       [2, 3]])

In [18]:
arr[:1,]

array([[1, 2, 3, 4, 5]])

In [19]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [21]:
arr*np.arange(0,10)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr1=arr
print(arr1)

[  0   1   2 100 100 100 100 100 100 100]


In [25]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr1=arr.copy()
print(arr)
arr1[3:]=1000
print(arr1)

[  0   1   2 100 100 100 100 100 100 100]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [27]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [28]:
val=2
arr*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [29]:
val=2
arr/2

array([ 0. ,  0.5,  1. , 50. , 50. , 50. , 50. , 50. , 50. , 50. ])

In [31]:
np.arange(0,10).reshape(5,2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.random.rand(3,3)

array([[0.05329852, 0.39888523, 0.97998332],
       [0.98008172, 0.25592011, 0.3027574 ],
       [0.77206202, 0.4179682 , 0.94925838]])

In [35]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[-0.97345547,  0.15356695, -0.33718533, -0.74050589],
       [ 0.07055258, -2.57477688, -1.61857481, -2.15731261],
       [ 0.70596591, -0.47104376, -0.18867172,  1.04775312],
       [-0.7488191 ,  0.58049046,  0.33818014,  1.78487056]])

In [36]:
np.random.randint(0,100,8).reshape(4,2)


array([[60, 22],
       [31, 64],
       [ 8,  7],
       [38, 34]])

In [37]:
np.random.random_sample((1,5))

array([[0.48441469, 0.49673973, 0.00540976, 0.62923498, 0.15671248]])